### ISSUE TITLE
[Bug] MC-147605 prevents EMI search bar from working

### ISSUE THREAD

**Issue by craftish37** [isXander/Debugify#109] opened 2022-06-15 19:31 UTC
### Bug Description

[EMI](https://github.com/emilyploszaj/emi/) search bar does not work properly with this fix

### How to Reproduce?

Install [EMI](https://github.com/emilyploszaj/emi/) and Debugify together, launch, open inventory and search something in the bar and try exiting the inventory

### Expected Behavior

Exiting succesfully the inventory

We should close the game to permit it

### Version

1.11.0

### Mod Loader Version

1.18.2 - fabric 0.55.1/QuiltMC 0.17.1 beta1

### Mod Loader

Quilt

### Logs or additional context

No logs for this bug, sadly

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment] 2022-06-16 16:11
related to #74

**Comment by DioEgizio** [comment] 2022-06-20 09:23
emi 1.19 is out

**Comment by Lancelotbronner** [comment] 2022-07-24 14:12
I have the same issue, Quilt 1.19

**Comment by isXander** [comment] 2022-08-02 13:11
Duplicate of #135

**Closed by isXander** 2022-08-02 13:11 UTC
Labels: bug, backburner, mod incompatibility
