### ISSUE TITLE
[Hello friends i've a crash] A crash

### ISSUE THREAD

**Issue by thelegitdolt** [isXander/Debugify#72] opened 2022-04-19 08:06 UTC
i am in 1.18.2, it crashes on start up

here are da loggies   https://gist.github.com/thelegitdolt/e601adb7bce49c6e67d4fe3b626632ec

i will test anything you guys want just give the word

**Comment by isXander** [comment] 2022-04-19 15:33
Duplicate of #71

**Closed as completed by isXander** 2022-04-19 15:33 UTC
Labels: bug, duplicate

**Comment by thelegitdolt** [comment] 2022-04-19 15:59
i'm sorry :((((((
