### ISSUE TITLE
[Patch request] MC-190836 - Chunk loading stops at high speeds

### ISSUE THREAD

**Issue by leonpano2006** [isXander/Debugify#159] opened 2022-09-26 05:52 UTC
### Mojang Bug Report ID

MC-190836

### Bug adhere to the guidelines.

- [X] I made sure that this bug adheres to the guidelines.

### Has not already been requested.

- [X] I am certain this patch has not already been requested.

### Has not already been implemented.

- [X] I know that this patch isn't already in the latest version of the mod.

### Existing implementation

None

**Comment by flashteens** [comment] 2022-09-26 15:48
I am the reporter of [MC-176240](https://bugs.mojang.com/browse/MC-176240), which was later considered a duplicate of MC-190836 by Mojang.

The bug [MC-190836](https://bugs.mojang.com/browse/MC-190836) demonstrates the **chunk loading problem** when a player is moving at a very high speed like 100 blocks per second, no matter which way the player is using.

In a nutshell, we just demonstrate the high speed scenario with "boat on blue ice" for easier demonstration. In fact, it has been a more serious problem especially for we map/datapack makers that are developing high-speed railway functions.

We really recommend you to check out the attached video on the Minecraft bug report to understand what we encountered.

**Comment by isXander** [comment] 2022-09-27 15:43
This will be difficult to diagnose :/

Not familiar with this area of the minecraft code-base but is peculiar that it happens at the same speed for everyone. I initially thought it would be just the game not being able to keep up but apparently not.

**Comment by isXander** [comment] 2022-09-27 16:04
After some testing I can't even reproduce it :/ This bug is simply down to the performance of the device, not being able to keep up with the speeds. If you can convince me otherwise, I'll re-open.

**Closed by isXander** 2022-09-27 16:04 UTC
Labels: patch request
