### ISSUE TITLE
[Crash] Summary of Crash

### ISSUE THREAD

**Issue by Jaedubu** [isXander/Debugify#134] opened 2022-08-01 10:28 UTC
### Crash Description

it is the only mod I have installed together with cloth api to see if it worked on its own and it crashed before the game starts in 1.19

### How to Reproduce?

install forge 41 for 1.19
install debugify 2.3.2
start the game
Crashes

### Expected Behavior

I expected the mod to run since I also installed cloth api and no other mods are installed except the tl skin cape.

### Version

2.3.2

### Mod Loader Version

1.19 - 41.1.0

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/CX7JxUU1

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment] 2022-08-02 13:12
Duplicate of #133

**Closed** 2022-08-02 15:53 UTC
Labels: bug, duplicate
