### ISSUE TITLE
Reappearing Blocks on Server

### ISSUE THREAD

**Issue by EndDragon438** [isXander/Debugify#251] opened 2023-06-12 19:51 UTC
### Bug Description

First noticed instamining netherrack. I am running Debugify as part of a client-side optimization/tweak pack, playing on a vanilla server. When mining, after the first block every block mined reappears without being broken, until I click again and it breaks one more block. Also occurs in singleplayer test world with the same pack.

Tested with 50-mod utility pack as well as a pack with just Debugify and dependencies. Same behaviour.
Attached are logs for the Debugify pack.

### How to Reproduce?

1: Create a modpack with Debugify and dependencies (fabric api and YetAnotherConfigLib)
2: load into a creative test world
3: get into a position to instamine blocks
4: mine away! see how after a bit only one block is broken per click

### Expected Behavior

I should be able to mine more than one block every time I click.

### Version

1.20+1.1

### Fabric/Quilt Loader Version

Fabric 0.14.21 for MC 1.20

### Logs or additional context

[latest.log](https://github.com/isXander/Debugify/files/11727769/latest.log)

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date fabric/quilt loader and mod version.

**Comment by Organ-donor** [comment] 2023-06-12 21:54
1) disable:
MC-46766
MC-159163
MC-165381
MC-176559
2) restart Minecraft.
3) bug is gone.
not sure which one of four causing bug, but that helped me, so it can work for you. =)

**Comment by isXander** [comment] 2023-06-12 22:37
Duplicate of #247 fixed in 1.20.1+1.0

**Closed** 2023-06-12 22:37 UTC
Labels: bug
