### ISSUE TITLE
[Bug] Summary of bug

### ISSUE THREAD

**Issue by djromrell** [isXander/Debugify#124] opened 2022-07-21 01:50 UTC
### Bug Description

Crashes the game, I know the issue is with MC-234898 because turning off in config fixed the crashing.

### How to Reproduce?

Crashes practically instantly when menu appears. 

### Expected Behavior

I was not doing anything with realms so it is odd receiving a realms bug.

### Version

1.10.0

### Mod Loader Version

1.18.2-40.1.68

### Mod Loader

Forge

### Logs or additional context

Crashreport for  "MC-234898": https://pastebin.com/ScXkkZid

### Has not been reported.

- [X] I made sure this bug hasn't already been reported.

### Is on most update to date version.

- [X] I made sure I am using the most up to date mod loader and mod version.

**Comment by isXander** [comment] 2022-07-21 08:58
Duplicate of #123

**Closed by isXander** 2022-07-21 08:58 UTC
Labels: bug

**Comment by djromrell** [comment] 2022-07-21 23:20
which mod are you considering like lithium cause I dont have lithium?
